### ISSUE TITLE
Example compile error

### ISSUE THREAD

**Issue by MarcusE1W** [Fabien-Chouteau/lvgl-ada#2]
Hi.

First of all, thanks. this looks like a great project.

During the build with `alr build` I get this error:
```
==============Error messages for file: /home/rock64/prog/ada/tst/3/lvgl_ada_examples_0.1.0_8267a841/alire/cache/projects/lvgl_ada_simulator_0.1.0_f4132af3/lvgl_ada_simulator.gpr
     1. with "gnat/sdlada.gpr";
             |
        >>> unknown project file: "gnat/sdlada.gpr"
```

The path for gnat/sdlada.gpr is not quite right, it should be `build/gnat/sdlada.gpr`, then it works.

Maybe there was a change in package sdlada ?

**Comment by Fabien-Chouteau** [comment]
Hi @MarcusE1W,

I actually think that this is related to a bug that is now fixed in `Alire`: https://github.com/alire-project/alire/pull/280

The project file should probably have `with "sdlada.gpr"` now.
Thank you for the report, I will try to fix this and make a new release as soon as possible.

It's nice to see someone interested in this project, I would happy to know what you plan to do with it :)

**Comment by Fabien-Chouteau** [comment]
In the meantime you can edit `alire/cache/projects/lvgl_ada_simulator_0.1.0_f4132af3/lvgl_ada_simulator.gpr` to change `with "gnat/sdlada.gpr";` to `with "sdlada.gpr";`.

**Comment by Fabien-Chouteau** [comment]
Alright @MarcusE1W I published a fix in Alire: https://github.com/alire-project/alire-index/pull/79

Since this is holiday season it might take some time to be integrated into the index (the process is not automated yet).

**Comment by MarcusE1W** [comment]
Thanks for the feedback.

I am looking for a solution to use Ada with the [PineTime](https://store.pine64.org/?product=pinetime-dev-kit) Dev Kit.

The display is naturally quite small. Could vlgl still fit?

**Comment by Fabien-Chouteau** [comment]
> I am looking for a solution to use Ada with the [PineTime](https://store.pine64.org/?product=pinetime-dev-kit) Dev Kit.

Nice! I remember someone else looking at running Ada on this watch, maybe it was you.

> The display is naturally quite small. Could vlgl still fit?

lvgl can fit on any screen I think.

**Comment by MarcusE1W** [comment]
Happy to confirm that all works now :-D

**Comment by Fabien-Chouteau** [comment]
Awesome, thanks for the update!
