### ISSUE TITLE
Canvas object not mapped ?

### ISSUE THREAD

**Issue by MarcusE1W** [Fabien-Chouteau/lvgl-ada#3]
Hi.

Do I see that right, there is no canvas object mapped in the Ada bindings ?

**Comment by Fabien-Chouteau** [comment]
Hi @MarcusE1W,

I added canvas support in the `1.0.0` release, I am not sure this widget is going to be very useful :)

**Comment by MarcusE1W** [comment]
Thanks Fabien.

I always seem to have slightly off target use-cases. I wanted to use the cavas to draw pixel for a mandelbrot programme ;-)
